language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t naveed019/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true naveed019/docker-react npm run test

deploy: 
  provider: elasticbeanstack
  region: ap-south-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-ap-south-1-293794245415
  bucket_path: docker-react
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY  
  secret_access_key:
    secure: $AWS_SECRET_KEY
