language: generic
sudo: required
services:
  - docker

before-install:
  - docker build -t naveed019/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true naveed019/docker-react npm run test